In [1]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [3]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [5]:
import numpy as np
a=np.zeros((2,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
import numpy as np
s=np.random.random([2,3])
print("\n array with random values \n",s)


 array with random values 
 [[0.24494589 0.68943763 0.65297137]
 [0.78825523 0.52887444 0.25750109]]


In [8]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8],[1,2,0,1]])
newarr=arr.reshape(4,3)
print(arr)
print(newarr)

[[1 2 3 4]
 [5 6 7 8]
 [1 2 0 1]]
[[1 2 3]
 [4 5 6]
 [7 8 1]
 [2 0 1]]


In [10]:
import numpy as op
flat=arr.flatten()
print(arr)
print(flat)

[[1 2 3 4]
 [5 6 7 8]
 [1 2 0 1]]
[1 2 3 4 5 6 7 8 1 2 0 1]


In [ ]:
print(a.ndim)

2


In [11]:
print(a.shape)

(3, 4)


In [12]:
print(a.dtype)

int64


In [13]:
print(a.size)

12


In [15]:
newtype=arr.astype('f')
print("\n convert array:\n",newtype)
print("\n convert array type:\n",newtype.dtype)


 convert array:
 [[1. 2. 3. 4.]
 [5. 6. 7. 8.]
 [1. 2. 0. 1.]]

 convert array type:
 float32


In [17]:
size=len(arr)
print(size)

3
